apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../webapp.yaml

namePrefix: "user02-"

labels:
  - pairs:
      app.kubernetes.io/owner: user02
    includeSelectors: true

images:
- name: myapp
  newName: rhapsody008/sample-nodejs-webapp
  newTag: user02-d7c0d31
